.PHONY: icons

icons:
	convert icon.png -resize 16x16 16.png
	convert icon.png -resize 24x24 24.png
	convert icon.png -resize 32x32 32.png
	convert icon.png -resize 48x48 48.png
	convert icon.png -resize 64x64 64.png
	convert 16.png 24.png 32.png 48.png 64.png icon.ico
